server:
  address: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

analytics:
  workers: 10
  batch_size: 1000
  batch_timeout: "1s"
  cache_size: 10000

monitoring:
  metrics_port: 9090
  health_check_interval: "10s"
  alert_thresholds:
    cpu_usage: 80.0
    memory_usage: 85.0
    error_rate: 5.0

log:
  level: "info"
  format: "json"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

database:
  host: "localhost"
  port: 5432
  username: "analytics"
  password: "password"
  database: "analytics"
  ssl_mode: "disable"
  max_connections: 100
  max_idle_connections: 10
  connection_max_lifetime: "1h"
