// https://practice.geeksforgeeks.org/problems/minimum-multiplications-to-reach-end/1

package main

import (
	"fmt"
	"math"
)

type Pair struct {
	node  int
	steps int
}

func minimumMultiplications(arr []int, start int, end int) int {

	const mod = 100000

	// distance array
	dist := make([]int, mod)
	for i := range dist {
		dist[i] = math.MaxInt32
	}

	queue := []Pair{{start, 0}}
	dist[start] = 0

	for len(queue) > 0 {

		cur := queue[0]
		queue = queue[1:]

		node := cur.node
		steps := cur.steps

		for _, val := range arr {

			num := (node * val) % mod

			if steps+1 < dist[num] {
				dist[num] = steps + 1

				if num == end {
					return steps + 1
				}

				queue = append(queue, Pair{num, steps + 1})
			}
		}
	}

	return -1
}

func main() {

	start := 3
	end := 30
	arr := []int{2, 5, 7}

	ans := minimumMultiplications(arr, start, end)
	fmt.Println(ans)
}

// Time Complexity : O(100000 * N)
// Where ‘100000’ are the total possible numbers generated by multiplication (hypothetical) and N = size of the array with numbers of which each node could be multiplied.
// Space Complexity :  O(100000 * N)
// Where ‘100000’ are the total possible numbers generated by multiplication (hypothetical) and N = size of the array with numbers of which each node could be multiplied. 100000 * N is the max possible queue size. The space complexity of the dist array is constant.