worker:
  workers: 5
  batch_size: 100
  batch_timeout: "5s"
  poll_interval: "1s"

log:
  level: "info"
  format: "json"

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

database:
  host: "postgres"
  port: 5432
  username: "analytics"
  password: "password"
  database: "analytics"
  ssl_mode: "disable"
  max_connections: 100
  max_idle_connections: 10
  connection_max_lifetime: "1h"
